miot/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from miot.views import page_views, poi_views, profile_views, static_views

urlpatterns = [
    # Routes related to the frontend (discover in two modes and about)
    url(r'^places$', poi_views.PointOfInterestListViewPos.as_view(), name="poi_list"),
    url(r'^map$', poi_views.PointOfInterestListViewMap.as_view(), name="poi_map"),
    url(r'^about$', static_views.AboutView.as_view(), name="about"),

    # The dashboard related routes
    url(r'^dashboard/$', profile_views.Dashboard.as_view(), name="dashboard"),

    # Routes for the creation of a new object
    url(r'^dashboard/new/pointofinterest', poi_views.PointOfInterestCreateView.as_view(), name="poi_create"),
    url(r'^dashboard/new/page/(?P<slug>[-\w]+)', page_views.PageCreateView.as_view(), name="page_create"),
    url(r'^dashboard/new/page', poi_views.PointOfInterestSelectView.as_view(), name="poi_select"),

    # Routes for the deletion of an object
    url(r'^dashboard/delete/pointofinterest/(?P<slug>[-\w]+)', poi_views.PointOfInterestDeleteView.as_view(), name="poi_delete"),
    url(r'^dashboard/delete/page/(?P<slug>[-\w]+)', page_views.PageDeleteView.as_view(), name="page_delete"),

    # Routes for the updates of an object
    url(r'^dashboard/edit/page/(?P<slug>[-\w]+)', page_views.PageUpdateView.as_view(), name="page_update"),
    url(r'^dashboard/edit/pages/(?P<slug>[-\w]+)', page_views.PoiPageUpdateView.as_view(), name="poi_page_update"),
    url(r'^dashboard/edit/beacon/(?P<identifier>[-\w]+)', profile_views.UpdateBeaconView.as_view(), name="beacon_update"),
    url(r'^dashboard/edit/profile/(?P<pk>[-\w]+)', profile_views.ProfileUpdateView.as_view(), name="profile_update"),
    url(r'^dashboard/edit/pointofinterest/(?P<slug>[-\w]+)', poi_views.PointOfInterestUpdateView.as_view(), name="poi_update"),

    # Route to manage lists
    url(r'^dashboard/switch$', page_views.ChangeOrder.as_view(), name="switch_page_order"),
    url(r'^dashboard/manage/pages$', page_views.PageManageListView.as_view(), name="page_manage"),
    url(r'^dashboard/manage/pointofinterests$', poi_views.PointOfInterestManageListView.as_view(), name="poi_manage"),
    url(r'^dashboard/manage/beacons$', profile_views.ManageBeaconsView.as_view(), name="beacon_manage"),
    url(r'^dashboard/statistics$', profile_views.StatisticsView.as_view(), name="statistics"),

    # Routes for the detailviews
    url(r'^p/(?P<slugPOI>[-\w]+)/(?P<slug>[-\w]+)', page_views.PageDetailView.as_view(), name="page_detail"),
    url(r'^p/(?P<slug>[-\w]+)/', poi_views.PointOfInterestDetailView.as_view(), name="poi_detail"),

    # Homepage
    url(r'^$', static_views.HomepageView.as_view(), name="homepage"),

]

miotProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^', include('miot.urls')),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/logout/$', logout, {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miot/models.py
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django_extensions.db.fields import AutoSlugField
from taggit.managers import TaggableManager
from django.contrib.gis.db import models as gmodels
from django.conf import settings
from django.dispatch import receiver
from hitcount.models import HitCountMixin
from hitcount.models import HitCount
from django.contrib.gis.geos import Point
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.measure import D
from miot.utils import *
from miotProject.settings import MIOT_LONG_URL_POI
from django.contrib import messages

USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

class Profile(models.Model):
    '''The profile model attached to a default django user model. It is used to
    have additional informations such as the estimote app credentials.'''
    user = models.OneToOneField(USER_MODEL, blank=True, null=True)
    estimote_app_id = models.CharField(max_length=120, blank=True, null=True)
    estimote_app_token = models.CharField(max_length=255, blank=True, null=True)

    def fetch_points_of_interests(self):
        '''Get all the points of interest of that profile.'''
        return PointOfInterest.objects.filter(creator=self).order_by("-created")

    def fetch_points_of_interests_hits(self):
        '''Get the hit count of the points of interest of that profile.'''
        return HitCount.objects.select_related().filter(object_pk__in=self.fetch_points_of_interests()).aggregate(Sum("hits"))

    def fetch_pages(self):
        '''Get the pages of that profile.'''
        return Page.objects.select_related().filter(poi__in=self.fetch_points_of_interests()).order_by("-created")

    def __str__(self):
        return self.user.username

class Category(models.Model):
    '''The model representation of a category. It has an emoji field that is not
    used for the moment.'''
    name = models.CharField(max_length=120)
    slug = AutoSlugField(populate_from='name')
    emoji_name = models.CharField(max_length=100, blank=True, null=True)
    short_description = models.CharField(max_length=255)
    parent = models.ForeignKey('self', blank=True, null=True, related_name="children")

    def __str__(self):
        return self.name

class PointOfInterest(models.Model, HitCountMixin):
    '''The point of interest model representation.'''
    name = models.CharField(max_length=120)
    slug = AutoSlugField(populate_from='name')
    short_url = models.URLField(max_length=50)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    featured_image = models.ImageField(upload_to="uploads/poi")
    position = gmodels.PointField()
    tags = TaggableManager()
    active = models.BooleanField(default=True)
    creator = models.ForeignKey(Profile, null=True, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_NULL)

    def get_ordered_pages(self):
        '''Get the pages of that model, ordered by index.'''
        return Page.objects.filter(poi=self).order_by("index")

    def __str__(self):
        return self.name

class Template(models.Model):
    '''A template model representation.'''
    name = models.CharField(max_length=120)
    slug = AutoSlugField(populate_from="name")
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    short_description = models.CharField(max_length=255)
    featured_image = models.ImageField(upload_to="uploads/templates")

    def __str__(self):
        return self.name

class Page(models.Model, HitCountMixin):
    '''Page model representation.'''
    title = models.CharField(max_length=120)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    last_updated = models.DateTimeField(auto_now=True, editable=False)
    content = models.TextField()
    poi = models.ForeignKey('PointOfInterest', on_delete=models.CASCADE)
    template = models.ForeignKey('Template', on_delete=models.CASCADE)
    slug = AutoSlugField(populate_from="title")
    index = models.IntegerField(default=0)

    def __str__(self):
        return self.title

@receiver(post_save, sender=USER_MODEL)
def create_user_profile(sender, instance, created, **kwargs):
    '''Triggers the creation of a profile when user is created.'''
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=USER_MODEL)
def save_user_profile(sender, instance, **kwargs):
    '''Save the profile instance after a save of user model.'''
    instance.profile.save()

@receiver(post_save, sender=PointOfInterest)
def create_poi_page(sender, instance, created, **kwargs):
    '''Create page and set short url when creating a point of interest.'''
    if created:
        long_url = "{0}/{1}".format(MIOT_LONG_URL_POI, instance.slug)
        instance.short_url = get_short_url(long_url)
        instance.save()
        Page.objects.create(poi=instance, title="{0} homepage".format(instance.name), content="Your content here.", template=Template.objects.first())

def get_near_poi(lat, longi):
    '''Get the nearest points of interest.'''
    location = Point(float(longi), float(lat))
    return PointOfInterest.objects \
        .filter(position__distance_lte=(location, D(km=10))) \
        .annotate(distance=Distance('position', location)) \
        .order_by('distance')

miot/forms.py
from mapwidgets.widgets import GooglePointFieldWidget
from miot.models import PointOfInterest, Page, Profile
from django import forms

class PointOfInterestForm(forms.ModelForm):
    '''The form for a point of interest.'''
    class Meta:
        model = PointOfInterest
        fields = ("name", "featured_image", "position", "tags", "active", "category")
        widgets = {
            'position': GooglePointFieldWidget,
        }

class PageForm(forms.ModelForm):
    '''The form for a page.'''
    class Meta:
        model = Page
        fields = ("title", "content", "template")

class EstimoteAppForm(forms.ModelForm):
    '''The form for a profile update (estimote credentials).'''
    class Meta:
        model = Profile
        fields = ("estimote_app_id", "estimote_app_token")

miot/views/page_views.py
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, View, DetailView
from miot.models import Page, PointOfInterest
from miot.forms import PointOfInterestForm, PageForm
from django.http import HttpResponse
from django.db.models import F
from django.db import transaction

from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt

from hitcount.views import HitCountDetailView

class PageDetailView(HitCountDetailView):
    '''The view for a page detail. It will display the page content and use the
    specific template that was chosen by the creator.'''
    model = Page
    template_name = "page_detail.html"
    count_hit = True

    def get_context_data(self, **kwargs):
        '''The get context data get the ordered pages in order to generate the
        navigation menu on the template.'''
        context = super(PageDetailView, self).get_context_data(**kwargs)
        context['ordered_pages'] = PointOfInterest.objects.get(slug=self.kwargs['slugPOI']).get_ordered_pages()
        return context

class PageManageListView(ListView):
    '''This views is used to see the list of pages that belong to the current user.'''
    model = Page
    template_name = "dashboard/page_list.html"

    def get_queryset(self):
        '''The queryset contains every pages in the points of interest of that user.'''
        return Page.objects.select_related().filter(poi__in=self.request.user.profile.fetch_points_of_interests())

class PoiPageUpdateView(LoginRequiredMixin, ListView):
    '''This page is used to display every page of a given point of interest
    belonging to the user.'''
    model = PointOfInterest
    template_name = "dashboard/manage-poi-pages.html"

    def get_context_data(self, **kwargs):
        '''The context data adds the slug of the poi to identify it.'''
        context = super(PoiPageUpdateView, self).get_context_data(**kwargs)
        context['poi'] = PointOfInterest.objects.get(slug=self.kwargs['slug'])
        return context

    def get_queryset(self):
        '''The get queryset fetch all the pages ordered by index for this poi.'''
        return Page.objects.filter(poi=PointOfInterest.objects.get(slug=self.kwargs['slug'])).order_by("index")

class PageCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    '''The page creation view.'''
    form_class=PageForm
    template_name = "dashboard/page_form.html"
    success_url="/dashboard"
    success_message = "%(title)s page was created successfully"

    def form_valid(self, form):
        '''When the form is valid, we set the point of interest of the created
        page and set the base index.'''
        form.instance.poi = PointOfInterest.objects.get(slug=self.kwargs["slug"])
        form.instance.index = Page.objects.filter(poi=form.instance.poi).count()
        return super(PageCreateView, self).form_valid(form)

class PageUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    '''The update page view.'''
    model = Page
    form_class=PageForm
    template_name="dashboard/page_form.html"
    success_url="/dashboard"
    success_message = "%(title)s was updated successfully"

class PageDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    '''The delete page view asking for confirmation on a specific template.'''
    model = Page
    template_name = "dashboard/page_delete.html"
    success_url = "/dashboard"
    success_message = "Page deleted successfully"

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(PageDeleteView, self).delete(request, *args, **kwargs)


class ChangeOrder(View):
    '''The method called when pages are reordered on the poi page list view.
    This could probably be optimized.'''
    def post(self, request, *args, **kwargs):
        oldIndex = request.POST.get("oldIndex")
        newIndex = request.POST.get("newIndex")

        if newIndex > oldIndex:
            lPages = Page.objects.filter(poi=PointOfInterest.objects.get(pk=request.POST.get("poi")), index__lte=newIndex).filter(index__gte=oldIndex).exclude(index=oldIndex)
            lPages.update(index= F('index') - 1)
        else:
            lPages = Page.objects.filter(poi=PointOfInterest.objects.get(pk=request.POST.get("poi")), index__gte=newIndex).filter(index__lte=oldIndex).exclude(index=oldIndex)
            lPages.update(index= F('index') + 1)
        cPage = Page.objects.filter(poi=PointOfInterest.objects.get(pk=request.POST.get("poi")), index=oldIndex).order_by("last_updated")
        p = cPage.first()
        p.index=newIndex
        p.save()

        return HttpResponse("ok")

miot/views/static_views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.conf import settings
from miot.models import PointOfInterest

class HomepageView(TemplateView):
    '''The simple homepage view.'''
    def get(self, request):
        context, context["pois"] = {}, PointOfInterest.objects.all()[:5]
        return render(request, "static/homepage.html", context)

class AboutView(TemplateView):
    '''The static about view.'''
    def get(self, request):
        return render(request, "static/about.html")

miot/templates/page_detail.html
{% extends "page_templates/"|add:page.template.slug|add:".html" %}

{% block title %}{{page.poi.name}} - {{page.title}}{% endblock %}
{% block the_menu_title %}{{page.poi.name}}{% endblock %}
{% block the_title %}{{page.title}}{% endblock %}
{% block the_category %}{{page.poi.name}}{% endblock %}
{% block the_bg %}{{page.poi.featured_image.url}}{% endblock %}

{% block content %}

<div class="container mt-4 pb-4">
  <div class="content">
    {{page.content|safe}}
  </div>
</div>

{% endblock %}

miot/templates/poi_detail.html
{% extends "page_templates/"|add:ordered_pages.first.template.slug|add:".html" %}

{% block title %}
{{poi.name}}
{% endblock %}

{% block the_menu_title %}{{poi.name}}{% endblock %}
{% block the_title %}{{poi.name}}{% endblock %}
{% block the_category %}{{poi.category.name}}{% endblock %}
{% block the_bg %}{{poi.featured_image.url}}{% endblock %}

{% block content %}




<div class="container mt-4 pb-4">

  <div class="content">
    {{poi.page_set.first.content|safe}}
  </div>

  <hr class="mx-3"/>

  <p class="text-muted"><i class="fa fa-eye fa-fw"></i>&nbsp;Visits : {{ hitcount.total_hits }}</p>
  <p class="text-muted"><i class="fa fa-link fa-fw"></i>&nbsp;Short URL : {{ poi.short_url }}</p>

  {% for t in poi.tags.all %}
  <span class="badge badge-default p-2 m-1"><a href="{% url "poi_list" %}?q={{t.name}}&amp;c=all" class="badge-link">{{t.name}}</a></span>
  {% endfor %}


  <hr class="mx-3"/>

  <h4>Similar points of interest</h4>
  <div class="row">
    {% for s in poi.tags.similar_objects|slice:"6" %}
    <div class="col-12 col-md-4 pl-0 ml-0 mt-3">
      <div class="container">
        <div class="card">
          <div class="card-block p-0" style="background-image:url('{{s.featured_image.url}}'); background-size: cover;">
            <div class="card-filter" style="background: rgba(0,0,0,.4); color: #f8f8f8;">
              <div class="p-4">
                <a href="{% url "poi_detail" s.slug %}" style="color: #f8f8f8;"><h4 class="card-title">{{s.name|truncatechars:15}}</h4></a>
              </div>
            </div>
          </div>
          <div class="card-footer text-muted">
            <span class="badge badge-default p-2">
              {{s.similar_tags}} similar tags
            </span>
          </div>
        </div>
      </div>
    </div>
    {% empty %}


      <div class="col-12">
        <div class="card text-center p-3">
          <div class="card-content">
            <i class="fa fa-fw fa-frown-o fa-3x text-muted"></i>
            <p><strong>No similar points of interest found.</strong></p>
          </div>
        </div>
      </div>


    {% endfor %}
  </div>

</div>

{% endblock %}

miot/templates/poi_list.html
{% extends "layout/base.html" %}

{% block title %}
Discover places
{% endblock %}


{% block content %}


<section class="jumbotron">
  <div class="container">
    <h1 class="jumbotron-heading mb-0">Discover</h1>
    <small class="text-muted">There are so many interesting things to see.</small>
    <form action=""  method="get" class="mt-3">
      <div class="form-group row">
        <div class="col-12">
          <div class="input-group">
            <input type="text" class="form-control" id="lgFormGroupInput" name="q" placeholder="museum" {% for key, value in request.GET.items %}{% if key == 'q' %}value="{{ value }}"{% endif %}{% endfor %}>
            <button type="submit" class="input-group-addon btn-primary"><i class="fa fa-fw fa-search"></i></button>
          </div>
        </div>
      </div>

      <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseMoreFilters" aria-expanded="false" aria-controls="collapseExample">
        More filters
      </button>
      <a href="{% url "poi_map" %}" class="btn btn-primary btn-sm">
        <i class="fa fa-fw fa-globe"></i>&nbsp;Switch to map mode
      </a>

      <div class="collapse pt-2" id="collapseMoreFilters">
        <div class="from-group">
          <select name="c" class="form-control">
            <option value="all" default="">Select category</option>
            {% for c in categories %}
            <option value="{{c.id}}">{{c.name}}</option>
            {% endfor %}
          </select>
        </div>
      </div>

    </form>
  </div>
</section>


{% if search %}

<div class="container">
  <div class="row">
    {% for p in object_list %}
    <div class="col-12 col-md-4 mb-3">
      <div class="card">
        <a href="{% url "poi_detail" p.slug %}" class="card-block p-0" style="background-image:url('{{p.featured_image.url}}'); background-size: cover;">
          <div class="card-filter h-100" style="background: rgba(0,0,0,.4); color: #f8f8f8;">
            <div class="p-4">
              <h3 class="card-title">{{p.name}}</h3>
              <p class="card-text">{{p.page_set.first.content|striptags|truncatechars_html:30}}</p>
            </div>
          </div>
        </a>
        <div class="card-footer text-muted">
          <a href="{% url "poi_list" %}?c={{p.category.id}}">{{p.category.name}}</a>
        </div>
      </div>
    </div>
    {% empty %}
      <div class="col-12">
      <div class="card">

        <div class="card-block text-center">
          <i class="text-muted fa fa-fw fa-frown-o fa-4x mb-3"></i>
          <p><strong>No results matching your query</strong></p>
          <small>Please try again with other filters.</small>
        </div>
      </div>
    </div>

    {% endfor %}
  </div>
</div>

{% if is_paginated %}
<div class="pagination">
  <span class="page-links">
    {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">previous</a>
    {% endif %}
    <span class="page-current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">next</a>
    {% endif %}
  </span>
</div>
{% endif %}

{% else %}

<div class="container">
  <div class="row">

    {% for p in object_list|slice:":3" %}
    <div class="col-12 col-md-4 mb-3">
      <div class="card h-100">
        <a href="{% url "poi_detail" p.slug %}" class="card-block p-0" style="background-image:url('{{p.featured_image.url}}'); background-size: cover;">
          <div class="card-filter h-100" style="background: rgba(0,0,0,.4); color: #f8f8f8;">
            <div class="p-4">
              <h3 class="card-title">{{p.name|truncatechars:30}}</h3>
              <p class="card-text">{{p.page_set.first.content|striptags|truncatechars_html:30}}</p>
            </div>
          </div>
        </a>
        <div class="card-footer text-muted">
            <a href="{% url "poi_list" %}?c={{p.category.id}}">{{p.category.name}}</a>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="container mt-5 mb-2">
      <h2>Near you</h2>
      <p class="lead text-muted">Find these points of interest a few steps away!</p>
    </div>
  </div>

  <div class="row">
    {% if nearPois %}
    {% for p in nearPois|slice:":8" %}
    <div class="col-12 col-md-3 mb-3">
      <div class="card h-100">
        <a href="{% url "poi_detail" p.slug %}" class="card-block p-0" style="background-image:url('{{p.featured_image.url}}'); background-size: cover;">
          <div class="card-filter h-100" style="background: rgba(0,0,0,.4); color: #f8f8f8;">
            <div class="p-4">
              <h4 class="card-title">{{p.name|truncatechars:30}}</h4>
            </div>
          </div>
        </a>
        <div class="card-footer text-muted">
            <a href="{% url "poi_list" %}?c={{p.category.id}}">{{p.category.name}}</a>- {{ p.distance }}
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="card col-12 py-3">
      <div class="card-block d-flex flex-column align-items-center">
        <i class="fa fa-map-marker text-muted" style="font-size: 5em;"></i>
        <p class="mt-3"><strong>Please share your location to see places near you.</strong></p>
      </div>
    </div>
    {% endif %}

  </div>
</div>



<div class="container">

  <div class="row mt-5">
    <div class="col-12 col-md-6 mb-5">

      <div class="row">
        <div class="container mb-2">
          <h2>Top featured</h2>
          <p class="lead text-muted">Most visited points of interest on this platform</p>
        </div>
      </div>

      <div class="list-group">
        {% for p in object_list %}
        <a href="{% url "poi_detail" p.slug %}" class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">{{p.name}}</h5>
            <small class="text-muted">by {{p.creator.user.username}}</small>
          </div>
          <small class="text-muted">
            {% for tag in p.tags.all %}
            {{tag.name}}
            {% endfor %}
          </small>
        </a>
        {% endfor %}
      </div>
    </div>

    <div class="col-12 col-md-6">

      <div class="row">
        <div class="container mb-2">
          <h2>Most used tags</h2>
          <p class="lead text-muted">Most common tags used to define places</p>
        </div>
      </div>

      <div class="card">
        <div class="card-block">
          {% for t in topTags %}
          <span class="badge badge-default p-2 m-1">
            <a class="badge-link" href="{% url "poi_list" %}?q={{t.name}}&amp;c=all">{{t.name}}</a>
          </span>
          {% endfor %}
        </div>
      </div>
    </div>

  </div>
</div>

{% endif %}


<script>
// We ask the position
{% if not nearPois %}
getLocation();
{% endif %}


function getLocation() {
  console.log("LOCATE");
  if (navigator.geolocation) {
    console.log("geoloc");
    navigator.geolocation.getCurrentPosition(function(pos){
      console.log("ghello")
      window.location = "/places?lat=" + pos.coords.latitude + "&lon=" + pos.coords.longitude + "{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}";
    });
  } else {
    alert("Please ! Let us use your gps");
  }
}


</script>


{% endblock %}

miot/templates/poi_list_map.html
{% extends "layout/base.html" %}


{% load render_bundle from webpack_loader %}

{% block title %}
Discover places
{% endblock %}


{% block content %}


<section class="jumbotron text-center mb-0 p-3">
  <div class="container">
    <form action=""  method="get" class="mt-3">
      <div class="form-group row">
        <div class="col-12">
          <div class="input-group">
            <input type="text" class="form-control" id="lgFormGroupInput" name="q" placeholder="museum" {% for key, value in request.GET.items %}{% if key == 'q' %}value="{{ value }}"{% endif %}{% endfor %}>
            <button type="submit" class="input-group-addon btn-primary"><i class="fa fa-fw fa-search"></i></button>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-12 d-flex justify-content-between">
          <button class="btn btn-primary btn-sm" type="button" data-toggle="collapse" data-target="#collapseMoreFilters" aria-expanded="false" aria-controls="collapseExample">
            More filters
          </button>
          <a href="{% url "poi_list" %}" class="btn btn-primary btn-sm">
            <i class="fa fa-fw fa-list"></i>&nbsp;Switch to list mode
          </a>
        </div>

        <div class="row">
          <div class="col-12">
            <div class="collapse pt-2 ml-2" id="collapseMoreFilters">
              <div class="from-group">
                <select name="c" class="form-control">
                  <option value="all" default="">Select category</option>
                  {% for c in categories %}
                  <option value="{{c.id}}">{{c.name}}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
          </div>
        </div>

      </div>

    </form>
  </div>
</section>

<div id="markers" style="display:none;">
  [
  {% for poi in object_list %}
  {
    "name": "{{poi.name}}",
    "slug": "{{poi.slug}}",
    "href": "{% url "poi_detail" poi.slug %}",
    "img": "{{poi.featured_image.url}}",
    "position": {
      "lat": "{{poi.position.get_y}}",
      "lon": "{{poi.position.get_x}}"
    }
  }{% if not forloop.last %},{% endif %}
  {% endfor %}
  ]
</div>



<div class="modal fade bd-example-modal-sm" id="noResultsModal" tabindex="-1" role="dialog" aria-labelledby="noResultsModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">No results</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <p class="text-muted">Please try again with other parameters.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<div class="container-fluid p-0">
  <div id="map-canvas" style="min-width: 100%; min-height: 80vh;"></div>
</div>

<script>

{% if not object_list %}
$('#noResultsModal').modal();
{% endif %}

{% if not pois %}
getLocation();
{% endif %}


function getLocation() {
  console.log("LOCATE");
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(function(pos){
      window.location = "/map?lat=" + pos.coords.latitude + "&lon=" + pos.coords.longitude + "{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}";
    });
  } else {
    alert("Please ! Let us use your gps");
  }
}


</script>


{% endblock %}

{% block scripts %}
{% render_bundle 'frontend' 'js' %}
{% endblock %}